services:
    # Development service with hot reloading
    dev:
        profiles:
            - dev
        build:
            context: .
            dockerfile: docker/Dockerfile.dev
        image: ghcr.io/cdot65/prisma-airs-mcp:dev-local
        container_name: prisma-airs-mcp-dev
        ports:
            - "3000:3000"
        volumes:
            # Mount source code for hot reloading
            - ./src:/app/src:ro
            - ./package.json:/app/package.json:ro
            - ./tsconfig.json:/app/tsconfig.json:ro
            # Persist node_modules
            - node_modules:/app/node_modules
        environment:
            - NODE_ENV=development
            - PORT=3000
            - LOG_LEVEL=debug
            # AIRS Configuration (override with .env file)
            - AIRS_API_URL=${AIRS_API_URL:-https://api.prisma-airs-test.example.com}
            - AIRS_API_KEY=${AIRS_API_KEY}
            # Optional configurations
            - CACHE_ENABLED=${CACHE_ENABLED:-true}
            - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-300}
            - CACHE_MAX_SIZE=${CACHE_MAX_SIZE:-1000}
            - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-true}
            - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
            - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-60000}
        env_file:
            - .env
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:3000/health",
                ]
            interval: 30s
            timeout: 3s
            retries: 3
            start_period: 10s
        restart: unless-stopped

    # Production service
    prod:
        profiles:
            - prod
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: production
        image: ghcr.io/cdot65/prisma-airs-mcp:latest
        container_name: prisma-airs-mcp-prod
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
            - PORT=3000
            - LOG_LEVEL=info
            # AIRS Configuration (must be provided)
            - AIRS_API_URL=${AIRS_API_URL}
            - AIRS_API_KEY=${AIRS_API_KEY}
            # Optional configurations
            - CACHE_ENABLED=${CACHE_ENABLED:-true}
            - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-300}
            - CACHE_MAX_SIZE=${CACHE_MAX_SIZE:-1000}
            - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-true}
            - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
            - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-60000}
        env_file:
            - .env
        healthcheck:
            test:
                [
                    "CMD",
                    "node",
                    "-e",
                    "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); });",
                ]
            interval: 30s
            timeout: 3s
            retries: 3
            start_period: 10s
        restart: unless-stopped
        # Resource limits (adjust based on requirements)
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
                reservations:
                    cpus: "0.25"
                    memory: 128M

volumes:
    node_modules:
