apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma-airs-mcp
spec:
  template:
    spec:
      containers:
      - name: prisma-airs-mcp
        image: ghcr.io/cdot65/prisma-airs-mcp:latest
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: development
        - name: LOG_LEVEL
          value: debug
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"