apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

labels:
- pairs:
    environment: development

resources:
- ../../base

replicas:
- name: prisma-airs-mcp
  count: 1

patches:
- path: deployment-patch.yaml

configMapGenerator:
- name: prisma-airs-mcp-config
  behavior: merge
  literals:
  - airs.api.url=https://service.api.aisecurity.paloaltonetworks.com
  - cache.ttl.seconds=60
  - rate.limit.max.requests=200
  - airs.default.profile.name=Prisma AIRS