apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma-airs-mcp
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - prisma-airs-mcp
              topologyKey: kubernetes.io/hostname
      containers:
      - name: prisma-airs-mcp
        image: ghcr.io/cdot65/prisma-airs-mcp:latest
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: production
        - name: LOG_LEVEL
          value: warn
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "2000m"