# Prisma AIRS MCP Documentation Site Configuration
title: Prisma AIRS MCP
description: AI Runtime Security through Model Context Protocol - Secure your AI applications with enterprise-grade threat detection
baseurl: "/prisma-airs-mcp"
url: "https://cdot65.github.io"
# theme: jekyll-theme-minimal  # Disabled to use custom layouts

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter_opts:
        css_class: "highlight"
        span:
            line_numbers: false
        block:
            line_numbers: false

# Collections
collections:
    developers:
        output: true
        permalink: /developers/:path/
    deployment:
        output: true
        permalink: /deployment/:path/
    prisma-airs:
        output: true
        permalink: /prisma-airs/:path/
    enterprise:
        output: true
        permalink: /enterprise/:path/
    api:
        output: true
        permalink: /api/:path/

# Default layouts
defaults:
    - scope:
          path: ""
          type: "developers"
      values:
          layout: "documentation"
          category: "developers"
    - scope:
          path: ""
          type: "deployment"
      values:
          layout: "documentation"
          category: "deployment"
    - scope:
          path: ""
          type: "prisma-airs"
      values:
          layout: "documentation"
          category: "prisma-airs"
    - scope:
          path: ""
          type: "enterprise"
      values:
          layout: "documentation"
          category: "enterprise"
    - scope:
          path: ""
          type: "api"
      values:
          layout: "api"
          category: "api"

# Site configuration
repository: cdot65/prisma-airs-mcp
google_analytics: UA-XXXXXXXXX-X
github_username: cdot65
github_repo: prisma-airs-mcp

# Plugins
plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

# Exclude from build
exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - .gitignore
    - vendor
