apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prisma-airs-mcp-server

labels:
- pairs:
    app.kubernetes.io/name: prisma-airs-mcp
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: kustomize

resources:
- deployment.yaml
- service.yaml
- ingressroute.yaml
- ingressroute-http.yaml

configMapGenerator:
- name: prisma-airs-mcp-config
  literals:
  - airs.api.url=https://service.api.aisecurity.paloaltonetworks.com
  - airs.default.profile.name=Prisma AIRS
  # - airs.default.profile.id=YOUR_PROFILE_ID
  - cache.enabled=true
  - cache.ttl.seconds=300
  - cache.max.size=1000
  - rate.limit.enabled=true
  - rate.limit.max.requests=100
  - rate.limit.window.ms=60000

# Note: Secrets should be created using the manage-secrets.sh script
# secretGenerator:
# - name: prisma-airs-mcp-secrets
#   literals:
#   - airs.api.key=PLACEHOLDER_API_KEY