# DO NOT COMMIT THIS FILE WITH REAL VALUES
# This is a template for creating the secret manually
#
# To create the secret:
# 1. Copy this file to a secure location
# 2. Replace PLACEHOLDER_API_KEY with your actual API key
# 3. Apply the secret: kubectl apply -f secret.yaml
# 4. Delete the file after applying
#
# Alternatively, create the secret directly:
# kubectl create secret generic prisma-airs-mcp-secrets \
#   --from-literal=airs.api.key='YOUR_ACTUAL_API_KEY' \
#   -n <namespace>

apiVersion: v1
kind: Secret
metadata:
  name: prisma-airs-mcp-secrets
  labels:
    app: prisma-airs-mcp
type: Opaque
stringData:
  airs.api.key: PLACEHOLDER_API_KEY
