apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma-airs-mcp
spec:
  template:
    spec:
      containers:
      - name: prisma-airs-mcp
        image: ghcr.io/cdot65/prisma-airs-mcp:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_ENV
          value: staging
        - name: LOG_LEVEL
          value: info